name: Publish

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: k64
            asset_name: k64-linux-amd64
          - os: windows-latest
            artifact_name: k64.exe
            asset_name: k64-windows-amd64
    steps:
    - uses: actions/checkout@v2
    - name: Set tag var
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v ./... -o ${{ matrix.artifact_name }}
    - name: Trigger GOPROXY
      run: GOPROXY=proxy.golang.org go list -m github.com/thetkpark/k64@${{ steps.vars.outputs.tag }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

